title: qrzn.xyz
tagline: Flow & recursion.
url: "https://qrzn23.github.io"
baseurl: ""

lang: en
timezone: Etc/UTC
future: true
theme: jekyll-theme-chirpy
theme_mode: dark

author:
  name: sourcer0r
  email: node@qrzn.xyz

github:
  username: qrzn23

social:
  name: Jan Landje
  email: jglandje@qrzn.xyz
  links:
    - https://qrzn.xyz
avatar: /assets/img/avatar.svg
favicon: /assets/img/favicons/favicon.svg

paginate: 10
paginate_path: "/page:num/"

collections:
  tabs:
    output: true
    sort_by: order

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache
  - jemoji
  - jekyll-redirect-from

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: sourcer0r
      comments: false
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      nav: true
